### ISSUE TITLE
Unable to specify JSON encoder

### ISSUE THREAD

**Issue by AlmightyOatmeal** [mwilliamson/jq.py#23]
```results = jq('.[].audits[].events[] | select(.field_name=="satisfaction_score" and .previous_value=="offered").value').transform(data, multiple_output=True, text_output=False)```

Results in:

```  File "/Users/jamie/Dropbox/work.SignalFX/data.PycharmProjects/python.CustomerSauce/zenstats.py", line 493, in report_csr
    results = jq('.[].audits[].events[] | select(.field_name=="satisfaction_score" and .previous_value=="offered").value').transform(data, multiple_output=True, text_output=False)
  File "jq.pyx", line 115, in jq._Program.transform (jq.c:1690)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 10, 17, 7, 6, 13, tzinfo=<DstTzInfo 'US/Pacific' PDT-1 day, 17:00:00 DST>) is not JSON serializable```

Are there plans to support jq structs instead of dumping Python structures to string then having jq reassemble them into C-structs?

**Comment by mwilliamson** [comment]
> 1) Why can't I specify my custom JSON encoder instead of the stock
> json.JSONEncoder?

No particular reason: it's just not been implemented (and the `text`
argument can be used if you want to control the encoding yourself).

> 2a) Why is this being converted to a string in the
> first place?

This was the easiest way of invoking jq as a library i.e. to give it a
string that should be parsed as JSON. It should also be possible to
construct jq structs directly, but using a string sufficed for me at
the time.

> 2b) Should I be dumping my nested dictionary/list JSON
> object to a string prior to using it in jq so I can use a custom JSON
> encoder?

If you want to use your own custom JSON encoder then yes, dumping it to
a string first would work. You'd then have to pass in the JSON text
using the `text` keyword argument. For instance:

    jq(program).transform({"a": 1})

should give the same result as:

    jq(program).transform(text='{"a": 1}')

> 2c) Is there any performance boost or penalty with the
> converting to string vs native Python objects?

At the moment, if you already have JSON text, then there's no point
parsing it since it'll get turned back into JSON text. If you're
starting with Python objects, it's up to you whether you pass those in
or whether to generate the JSON text yourself and use the `text`
argument. These bindings just use `json.dumps()`, so whether it's faster
to do it yourself or not depends on whether you can generate the JSON
text faster than `json.dumps()`.

> 3) Why is there
> literally no documentation on the `transform()` method? From the main
> README, I see there are 3 arguments possible with [0] always being
> the data object but two keyword args -- are there more? 

The README describes the various possible arguments you can pass in
with explanations and examples (none of which use [0] as the data
object), which I'd consider more than "literally no
documentation" (unless we're looking at different pages? I'm looking
at the README on GitHub [1]). There aren't any additional arguments
beyond those described.

[1] https://github.com/mwilliamson/jq.py

I admit the documentation is fairly short, but the interface is rather
small: most of the interesting functionality comes from the jq programs
you can write, for which it seems sensible to defer to their
documentation.

**Comment by mwilliamson** [comment]
Closing since the functionality is supported by using the `text` keyword argument, feel free to reopen if that doesn't work for you for some reason. Happy to look at pull requests that convert directly to jq structs if that improves performance.
